name: Slither Security Audit

on:
    push:
        branches: [main]

jobs:
    analyze:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Run Slither
              uses: crytic/slither-action@v0.3.0
              id: slither
              with:
                  node-version: 18
                  fail-on: none
                  target: ./backend/contracts/Voting.sol
                  slither-args: --print human-summary
