name: Mythril Security Audit

on:
    push:
        branches: [main]

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2
            -   name: Mythril Setup
                run: pip3 install mythril
            -   name: Run Mythril
                run: myth analyze ./contracts/Voting.sol
