name: Slither Security Audit

on:
    push:
        branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: yarn install
      - uses: actions/checkout@v3
      - uses: crytic/slither-action@v0.3.0
